
pdf:
	pdflatex survey
	biber survey
	pdflatex survey
	pdflatex survey

clean:
	rm -rf $(PAPER).pdf *.ps *.blg *.bbl *.dvi *.aux *.dvi *.log *~ core *.lbl
	rm -rf *.brf *.idx *.ilg *.ind *.lof *.lot *.out *.toc
	rm -rf *.bbl *.bcf *.blg *.fdb_latexmk *.fls *.lol


